### PR TITLE
final_worker_video_urls_setup

### PR DESCRIPTION
**Pull request by DmitriiTsy**
- [x]  frontend hotfix  (without ready to go JSON from backend) 
- [ ]  backend JSON short summary for each worker response 
- [ ]  backend JSON for each video => thumbnail url, videoURL, start + end, confidence rate, tittle for each video 
- [ ] backend => hide all irrelevant information from the user, such as index IDs, etc 
- [ ] frontend => update the frontend to handle all changes with JSON

When the URL of the clip arrives, we need to display it gracefully using a video player or players, so that the user can launch, play, and interact with the video on the frontend

image

### CODE REVIEW

**Comment by kingsotn-twelve** [comment]
1. what is the functional use of having summary for each worker response? im trying to understand if this is necessary, as it involves another openai short summary call and more state management on the backend.

2. wdym by hide all info from the user? every item is streamed via astream_events. how it is hidden depends on how the frontend parses that stream?

**Comment by DmitriiTsy** [comment]
Thanks for your comments @kingsotn-twelve 

1.  I believe the main idea is to provide short summary about each worker's actions, helping the user decide whether to click on the worker to view additional details about the current state. We can make it simpler by using this summary only for the final worker (make it only one call at the end, we can discuss it on the next meeting with Sean  @sean-twelvelabs and James @james-le-twelve-labs ) 

2.  Right now workers are providing some extra information for the user that they don't need to see, such as the list of index IDs or similar details. So in ideal world they should be able to see only relevant information without this extra data

**Comment by DmitriiTsy** [comment]
We implemented this functionality in a different way, with more focus on types directly from Langgraph, which is helpful. Therefore, we can close this P

**Comment by james-le-twelve-labs** [comment]
@DmitriiTsy Sounds good!

**Pull request closed without merging**
