### PR TITLE
aspect_ratio

### PR DESCRIPTION
**Pull request by DmitriiTsy**
This update improves the video editing function to handle different aspect ratios more effectively. It now scales all input videos to a consistent target resolution (1280x720)  and sets a Sample Aspect Ratio (SAR), ensuring compatibility & accessibility across different input formats. 
 
The function also includes improved error handling and more informative logging, making it more robust and easier to debug when processing multiple video clips later

### CODE REVIEW

**Comment by DmitriiTsy** [comment]
Screenshot 2024-10-03 at 2 43 42 PM

**Comment by james-le-twelve-labs** [comment]
@kingsotn-twelve @DmitriiTsy Looks like there are conflicts that must be resolved in order to merge this PR?

**Comment by DmitriiTsy** [comment]
I'll get back to it and resolve asap @james-le-twelve-labs

**Comment by DmitriiTsy** [comment]
We have a lot of new functionality from the MLSE hotfix, which includes some fixes from it, so this PR might be closed

**Comment by james-le-twelve-labs** [comment]
@DmitriiTsy Sounds good!

**Pull request closed without merging**
