### PR TITLE
handle exit from jockey terminal

### PR DESCRIPTION
**Pull request by ojadeyemi**
Allowed user to exit jockey terminal without throwing errors.

It won't kill the terminal unless the user has interacted with the jockey.

### CODE REVIEW

**Review by james-le-twelve-labs — DISMISSED** [review]
All makes sense!

**Comment by ojadeyemi** [comment]
I have noticed that **GPT-4** as the worker node LLM significantly improves jockey compared to gpt.3.5 models.
**GPT-4o** also outperforms **GPT-4** and is much cheaper.

Also, as a side note, the **GPT-4o mini** works well for all llms for all simple and medium-level tasks. It seems to have a shorter context window compared to just **GPT-4o**

**Comment by TravisCouture** [comment]
@james-le-twelve-labs @ojadeyemi The additional of exiting the terminal is perfect but the other changes should be eparated out into another PR. With the recent releases of GPT-4o mini and Llama 3.1, I suspect those will likely be more appropriate options for the workers. This is something we can test :)

**Comment by james-le-twelve-labs** [comment]
@ojadeyemi Does your PR address this issue? https://github.com/twelvelabs-io/tl-jockey/issues/35

**Comment by ojadeyemi** [comment]
No, it does not. This is only for the jockey terminal.

**Review by james-le-twelve-labs — COMMENTED** [review]
@ojadeyemi Can you provide a concise description of this PR in a few sentences?

**Comment by ojadeyemi** [comment]
Previously, when exiting jockey on the terminal (by Ctrl C) throughs in an `EOFError`. It also kills the terminal (at least on my Windows 11 ). Resulting in starting a new terminal to rerun it.
Now we can safely kill and restart jockey terminal as pleased.


Screenshot 2024-09-06 200510

**Comment by DmitriiTsy** [comment]
Screenshot 2024-09-25 at 1 22 21 PM

Works great, thank you @ojadeyemi

**Comment by kingsotn-twelve** [comment]
what was the reason for changing this from v2 -> v1?

`async for event in jockey.astream_events(jockey_input, {"configurable": {"thread_id": session_id}}, version="v1"):`

**Comment by ojadeyemi** [comment]
Just a typo, as this fix was made when it was still v1

**Comment by kingsotn-twelve** [comment]
I think moving to V2 makes sense because it simplifies outputs, improves performance by removing unnecessary steps, and fixes issues in V1, making event handling more reliable and easier to work with

please see the following for references. what do you think?

https://python.langchain.com/docs/versions/v0_2/migrating_astream_events/#removed-on_tool_stream
https://github.com/langchain-ai/langchain/pull/21638

**Review by kingsotn-twelve — APPROVED** [review]

**Pull request merged**
