### PR TITLE
updated llm model versions

### PR DESCRIPTION
**Pull request by ojadeyemi**
GPT 4o models perform exceptionally better than GPT 4 and GPT 3.5 turbo models.

### CODE REVIEW

**Comment by DmitriiTsy** [comment]
Thank you @ojadeyemi => these changes make sense, and we should frequently check for better versions of GPT or other models to stay up to date

**Comment by kingsotn-twelve** [comment]
The successor to gpt-3.5 should be [gpt-4o mini](https://platform.openai.com/docs/models/gpt-3-5-turbo). Did you mean to use 4o mini instead?

#81 did a good job in explaining differences in inference costs.

**Comment by ojadeyemi** [comment]
I changed to 4 a while ago, but 4o would be preferred.
I kept 4o instead of 4o mini for the supervisor and planner because it does better when the user prompt is more complex than 4o-mini.

Hopefully, we can have more LLM options outside of GPT in the future.

**Comment by kingsotn-twelve** [comment]
would you be open to writing a more generalized solution allowing users to specify their model? perhaps in the .env file to make model changes more general.

we should also tie this in with #81 and support other models too.

**Review by kingsotn-twelve — APPROVED** [review]

**Pull request merged**
